FROM ubuntu:latest

RUN apt update

RUN apt upgrade -y

RUN apt install openssh-server openssh-client -y

RUN useradd -m richard

RUN echo 'richard:123456' | chpasswd

CMD ["service", "ssh", "start", "-D"]