FROM nginx:latest

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./nginx/default.conf /etc/nginx/conf.d

RUN mkdir /etc/nginx/ssl

COPY ./nginx/certificado.crt /etc/nginx/ssl

COPY ./nginx/chave_privada.key /etc/nginx/ssl

COPY ./nginx/certificado2.crt /etc/nginx/ssl

COPY ./nginx/chave_privada2.key /etc/nginx/ssl

